### PR TITLE
Added option to choose amount of characters before starting the search

### PR DESCRIPTION
**Pull request by IssamElNass**
I've added the option to give an amount of characters before starting the search.

### CODE REVIEW

**Review by larsdroid — APPROVED** [review]

**Comment by larsdroid** [comment]
Commit 33e9969 looks like a very useful addition. Please merge as this would be helpful to many.
Commit 36bc8c7 is to be ignored.
Commit 961ad1a (setting the default chars to two) is optional.

**Review by alexrindone — COMMENTED** [review]
This looks great, and I love the idea. Anyway you can supply a test for this property? Thank you!

**Comment by alexrindone** [comment]
@larsdroid thanks for taking a look at this. I'd love to get a test for the functionality. I know it's super straight forward but any chance we can get one added? Thank you!

**Comment by alexrindone** [comment]
@IssamElNass @larsdroid I added this functionality in, but had to do some tweaking and run the tests for code coverage. Thank you!

**Pull request closed without merging**
