### PR TITLE
List container fix

### PR DESCRIPTION
**Pull request by maykhid**
based on [issue](https://github.com/alexrindone/flutter_textfield_search/issues/36)

worked on:
- the result container expands to accommodate longer lists.

added 

- scrollbar for a list with room for tweaking
- shapeborder to allow for styling the container (not related to the issue)

@alexrindone Please review

### CODE REVIEW

**Comment by alexrindone** [comment]
Thank you for the PR! I'll review this in a bit. Were there any tests you are able to write to add for code coverage?

**Comment by maykhid** [comment]
I didn't write any new tests

**Comment by alexrindone** [comment]
Alright, we need some tests and an implementation for the example @maykhid

**Comment by maykhid** [comment]
@alexrindone Okay. Have you looked at the code? Do you have any features in mind I should be doing a test for?

**Comment by alexrindone** [comment]
@maykhid I did take a look at the code, and you had some great ideas there! One thing that I'll show you is that I built out a way to accept a ScrollbarTheme so that we don't have to worry about the extra class you were creating with very specific properties. This makes it a little bit more extensible as a library, while allowing the user to use something that's already built within flutter for handling the design of the scrollbar. I'll have a PR up and deployed today hopefully. 

As far as tests go, when writing them you would want to make sure the lines of code you write are covered by tests that make sure the widgets you added are in fact within the widget tree, and have the properties and styling you would expect for the widget you were using. Let me know if you want more clarity.

**Comment by maykhid** [comment]
@alexrindone I saw your recent push to the master branch and I saw what you did with the Scrollbar theme, pretty cool. I guess with that implementation, I'll be removing my implementation of the Scroll from my code.

Also, what did you think of the way I Implemented the height of the search result overlay? I couldn't think of a way to make it truly flexible depending on the number of items on the list. I think making the list overlay extend longer would be pretty cool.

As for the tests I'll be jumping on that soon. Thanks.

**Comment by arindone1679** [comment]
So I actually implemented something for the height, which was the
itemsInView property (naming is always tough) based on what you had showed
for setting a height. It's a little more dynamic where it's default is 3
items high, but if you want more you can set it higher, but it will take
whatever result is smaller, so if you have 3 items found, but set 5 items
in view, then it will only be as high as the three items found. Does that
work or would you rather have the white space if there are 3 items but you
had the height much larger? As far as tests, take a look at the changes I
made for tests and it should give you an idea on how to write them. Flutter
front end testing can be a little strange at first!

**Comment by maykhid** [comment]
Actually, no. I didn't.

**Pull request closed without merging**
